### ISSUE TITLE
PosixPath error after updating to python 3.9.6

### ISSUE THREAD

**Issue by rodolphosilva** [incuna/django-wkhtmltopdf#185]
Guys, 

I'm working on a project with Python 3.9.6 and I'm facing an attribute error within the function ``make_absolute_paths``:

`AttributeError: 'PosixPath' object has no attribute 'endswith'`

I'm not sure but I think the fact that I'm using pathlib has something to do with it, since I have already faced another problem just like that.
